//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public string idEmpleado { get; set; }
        public string TipoEmpleado { get; set; }
        public string NombreUsuario { get; set; }
        public string Contrasena { get; set; }
        public Nullable<System.DateTime> FechaUltimoAcceso { get; set; }
    
        public virtual Persona Persona { get; set; }
    }
}
