//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PedidoDomicilio
    {
        public int idPedido { get; set; }
        public string Comentario { get; set; }
        public Nullable<System.DateTime> HoraSalida { get; set; }
        public string Repartidor { get; set; }
    
        public virtual Pedido Pedido { get; set; }
    }
}
