//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pedido()
        {
            this.PedidoProducto = new HashSet<PedidoProducto>();
        }
    
        public int idPedido { get; set; }
        public Nullable<System.DateTime> FechaPedido { get; set; }
        public Nullable<int> NumeroMesa { get; set; }
        public Nullable<int> Estatus { get; set; }
        public Nullable<int> Cliente { get; set; }
        public Nullable<int> Empleado { get; set; }
        public Nullable<int> DiaVenta { get; set; }
    
        public virtual Cliente Cliente1 { get; set; }
        public virtual Empleado Empleado1 { get; set; }
        public virtual Estatus Estatus1 { get; set; }
        public virtual PedidoDomicilio PedidoDomicilio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PedidoProducto> PedidoProducto { get; set; }
        public virtual DiaVenta DiaVenta1 { get; set; }
        public virtual DiaVenta DiaVenta2 { get; set; }
    }
}
