//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductoInventario
    {
        public int Inventario { get; set; }
        public int Producto { get; set; }
        public Nullable<int> CantidadIngreso { get; set; }
        public Nullable<double> PrecioCompra { get; set; }
        public Nullable<System.DateTime> FechaIngreso { get; set; }
        public Nullable<System.DateTime> Caducidad { get; set; }
    
        public virtual Inventario Inventario1 { get; set; }
        public virtual Producto Producto1 { get; set; }
    }
}
