//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecetaIngrediente
    {
        public int idReceta { get; set; }
        public int idProductoIngrediente { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<double> PrecioUnitario { get; set; }
    
        public virtual ProductoIngrediente ProductoIngrediente { get; set; }
        public virtual Receta Receta { get; set; }
    }
}
