//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecetaIngrediente
    {
        public int idReceta { get; set; }
        public int idProductoIngrediente { get; set; }
        public Nullable<int> Cantidad { get; set; }
        public Nullable<double> PrecioUnitario { get; set; }
    
        public virtual ProductoIngrediente ProductoIngrediente { get; set; }
        public virtual Receta Receta { get; set; }
    }
}
