//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UbicacionProducto
    {
        public int Ubicacion { get; set; }
        public int Producto { get; set; }
        public Nullable<int> Cantidad { get; set; }
    
        public virtual Producto Producto1 { get; set; }
        public virtual Ubicacion Ubicacion1 { get; set; }
    }
}
